{
 "title": "Dummy DevOps Dashboard",
 "description": "Dummy dashboard for DevOps Homework",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "goprom metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jobs_processed_total)", "legendFormat": "Total Jobs" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jobs_processed_total{result=\"success\"})",
     "legendFormat": "Total Jobs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jobs_processed_total{result=\"success\"})",
     "legendFormat": "Total Jobs"
    }
   ]
  },
  {
   "title": "Total Jobs per Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (instance) (jobs_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node1-worker",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_processed_total{instance=\"192.168.99.101:8081\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "node2-worker",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_processed_total{instance=\"192.168.99.102:8081\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "node3-worker",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_processed_total{instance=\"192.168.99.103:8081\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Docker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Containers by node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=\"cadvisor:8080\"}) > 0)",
     "legendFormat": "node1"
    },
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=\"192.168.99.102:8080\"}) > 0)",
     "legendFormat": "node2"
    },
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=\"192.168.99.103:8080\"}) > 0)",
     "legendFormat": "node3"
    }
   ]
  }
 ]
}