global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  
  # Local Prometheus instance
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Three Nodeexporter instances
  - job_name: 'nodeexporter'
    static_configs:
      - targets: [
          '192.168.99.201:9100',
          '192.168.99.202:9100',
          '192.168.99.203:9100'
        ]

  # Three cAdvisor instances
  - job_name: 'cadvisor'
    static_configs:
      - targets: [
          '192.168.99.201:8888',
          '192.168.99.202:8888',
          '192.168.99.203:8888'
        ]
