version: "3.4"

services:

  worker:
    image: shekeriev/goprom
    container_name: ${HOSTNAME:-unknown}-worker
    ports:
      - 8081:8080

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    container_name: ${HOSTNAME:-unknown}-nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    restart: unless-stopped
    ports:
      - 9100:9100
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: ${HOSTNAME:-unknown}-cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    command:
      - '--housekeeping_interval=15s'
      - '--docker_only=true'
      - '--store_container_labels=false'
      - '--whitelisted_container_labels=org.label-schema.group,com.docker.compose.project,com.docker.compose.service'
    ports:
      - 8080:8080
    labels:
      org.label-schema.group: "monitoring"

