{
 "title": "Radoslav's Exam DevOps Dashboard 26/03/2023",
 "description": "Exam dashboard for DevOps 26/03/2023",
 "tags": [ "docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Docker Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "All Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Containers by machine",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=\"192.168.99.201:8888\"}) > 0)",
     "legendFormat": "pipelines"
    },
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=\"192.168.99.202:8888\"}) > 0)",
     "legendFormat": "containers"
    },
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=\"192.168.99.203:8888\"}) > 0)",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}