global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.99.101:9323']

  - job_name: 'application'
    static_configs:
      - targets: ['192.168.99.101:8081']
      - targets: ['192.168.99.101:8082']
