version: "3.8"
services:
    web:
        image: <docker-hub-account-name>/bgapp-web
        ports:
            - 80:80
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: <docker-hub-account-name>/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
