global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  
  # Local Prometheus instance
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Three Nodeexporter instances
  - job_name: 'nodeexporter'
    static_configs:
      - targets: [
          'nodeexporter:9100',
          '192.168.99.102:9100',
          '192.168.99.103:9100'
        ]

  # Three cAdvisor instances
  - job_name: 'cadvisor'
    static_configs:
      - targets: [
          'cadvisor:8080',
          '192.168.99.102:8080',
          '192.168.99.103:8080'
        ]
  
  # Two worker instances
  - job_name: 'worker'
    static_configs:
      - targets: [
          '192.168.99.101:8081',
          '192.168.99.102:8081',
          '192.168.99.103:8081'
        ]


# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets: 
#       - 'alertmanager:9093'