# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-8"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.99.101"
    server.vm.provision "shell", path: "add-hosts.sh"
    server.vm.provision "shell", path: "install-elastic-stack.sh"

    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 2
    end
    
    server.vm.synced_folder "files/", "/vagrant"
  end
  
  config.vm.define "client1" do |client1|
    client1.vm.box = "shekeriev/centos-stream-8"
    client1.vm.hostname = "client1"
    client1.vm.network "private_network", ip: "192.168.99.102"
    client1.vm.provision "shell", path: "add-hosts.sh"
    client1.vm.provision "shell", path: "install-metricbeat-centos.sh"

    client1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
    client1.vm.synced_folder "files/", "/vagrant"
  end
  
  config.vm.define "client2" do |client2|
    client2.vm.box = "shekeriev/debian-11"
    client2.vm.hostname = "client2"
    client2.vm.network "private_network", ip: "192.168.99.103"
    client2.vm.provision "shell", path: "add-hosts.sh"
    client2.vm.provision "shell", path: "install-metricbeat-debian.sh"

    client2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--usb", "on"]
      v.customize ["modifyvm", :id, "--usbehci", "off"]
    end
    client2.vm.synced_folder "files/", "/vagrant"
  end
  
end
